- name: Add nfs-subdir-external-provisioner repository
  community.kubernetes.helm_repository:
    name: nfs-subdir-external-provisioner
    repo_url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/

- name: Install nfs-subdir-external-provisioner
  community.kubernetes.helm:
    name: nfs-subdir-external-provisioner
    chart_ref: nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
    release_namespace: kube-system
    kubeconfig: ~/.kube/config
    create_namespace: true
    values:
      nfs:
        server: "{{ nfs_server }}"
        path: "{{ nfs_path }}"

- name: Install Flask application using Helm
  community.kubernetes.helm:
    name: flaskapp
    chart_ref: "{{ PATH_to_helm_chart }}"
    release_namespace: default
    kubeconfig: ~/.kube/config
    create_namespace: true

- name: Install mysql using Helm
  community.kubernetes.helm:
    name: mysql
    chart_ref: "{{ PATH_to_helm_chart_sql}}"
    release_namespace: default
    kubeconfig: ~/.kube/config
    create_namespace: true
