---

- name: Prepare Cluster
  hosts: k8s_cluster
  roles:
  - k8s_cluster

- name: Init Cluster
  hosts: control_plane
  roles:
  - k8s-master

- name: Join Worker Nodes
  hosts: workers
  roles:
  - k8s-worker

- name: Setup NFS Server
  hosts: nfs
  roles:
  - k8s_nfs
